/*
 * Licensing, over a real socket, with Stripe's own signing.
 *
 * The webhook is the part that has to be right: it is the only endpoint on this
 * service that anyone on the internet can reach and that hands out something
 * worth money. Its signatures here are generated by Stripe's own library, so a
 * verifier that accepted the wrong thing would be caught — which is the reason
 * the library is a dependency at all.
 */

import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Stripe from 'stripe';
import { after, describe, it } from 'node:test';

import { AnalysisCache } from '../../server/cache.mjs';
import { decideFromEvent } from '../../server/billing.mjs';
import { createAnalysisServer } from '../../server/index.mjs';
import {
  LicenceStore,
  isLicenceKey,
  issueLicence,
  newLicenceKey,
  revokeLicence,
  verifyLicence,
} from '../../server/licence.mjs';

const WEBHOOK_SECRET = 'whsec_test_secret_for_the_suite';
const stripe = new Stripe('sk_test_not_a_real_key');

const directories = [];
const temporary = (prefix) => {
  const directory = mkdtempSync(join(tmpdir(), prefix));
  directories.push(directory);
  return directory;
};

after(() => {
  for (const directory of directories) rmSync(directory, { recursive: true, force: true });
});

/* A billing double that verifies signatures for real and never calls Stripe. */
const billingDouble = (overrides = {}) => ({
  constructEvent: (raw, signature) => {
    try {
      return stripe.webhooks.constructEvent(raw, signature, WEBHOOK_SECRET);
    } catch (cause) {
      const error = new Error(`Webhook signature rejected: ${cause.message}`);
      error.code = 'BAD_SIGNATURE';
      throw error;
    }
  },
  createCheckout: async ({ plan }) => ({ id: `cs_test_${plan}`, url: `https://checkout.stripe.test/${plan}` }),
  ...overrides,
});

const sign = (payload, timestamp = Math.floor(Date.now() / 1000)) =>
  stripe.webhooks.generateTestHeaderString({
    payload,
    secret: WEBHOOK_SECRET,
    timestamp,
  });

function completedSession(overrides = {}) {
  return JSON.stringify({
    id: 'evt_test_1',
    type: 'checkout.session.completed',
    data: {
      object: {
        id: 'cs_test_session_1',
        payment_status: 'paid',
        customer: 'cus_test_1',
        subscription: 'sub_test_1',
        customer_details: { email: 'dpo@example.fr' },
        metadata: { plan: 'pro' },
        ...overrides,
      },
    },
  });
}

async function start(options = {}) {
  const licences = new LicenceStore(temporary('consent-audit-licences-'));
  const server = createAnalysisServer({
    cache: new AnalysisCache(temporary('consent-audit-cache-')),
    ask: async () => ({ model: 'stub', mentions: [] }),
    licences,
    billing: billingDouble(),
    ...options,
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  return {
    licences,
    origin: `http://127.0.0.1:${server.address().port}`,
    close: () => new Promise((done) => server.close(done)),
  };
}

const post = (origin, path, body, headers = {}) =>
  fetch(`${origin}${path}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...headers },
    body: typeof body === 'string' ? body : JSON.stringify(body),
  });

describe('the licence key', () => {
  it('is readable off an invoice, and validates its own shape', () => {
    const key = newLicenceKey();
    assert.match(key, /^CA-[0-9A-Z]{4}(-[0-9A-Z]{4}){3}$/);
    assert.equal(isLicenceKey(key), true);
    /* The characters that get misread are not in the alphabet. */
    assert.equal(/[ILOU]/.test(key.slice(3)), false);
    assert.equal(isLicenceKey('CA-XXXX'), false);
    assert.equal(isLicenceKey(''), false);
  });

  it('is stored under its hash, not itself', () => {
    const store = new LicenceStore(temporary('consent-audit-licences-'));
    const { record } = issueLicence(store, { plan: 'pro', sessionId: 'cs_1' });

    const onDisk = JSON.stringify(store.all());
    assert.ok(onDisk.includes(record.key), 'the record itself holds the key');
    /* …but the filename does not, so a directory listing is worthless. */
    const names = store.all().length;
    assert.equal(names, 1);
    assert.equal(store.read(record.key).key, record.key);
  });
});

describe('verifying a licence', () => {
  const store = () => new LicenceStore(temporary('consent-audit-licences-'));

  it('answers with the plan, when it should be asked again, and when it ends', () => {
    const licences = store();
    const { record } = issueLicence(licences, { plan: 'pro', sessionId: 'cs_2', now: 1_000 });
    const answer = verifyLicence(licences, record.key, { now: 2_000 });

    assert.equal(answer.valid, true);
    assert.equal(answer.plan, 'pro');
    assert.equal(answer.entitlements.policyAnalysis, true);
    assert.equal(answer.recheckAfter, 2_000 + 7 * 24 * 60 * 60 * 1000);
    assert.ok(answer.expiresAt > 2_000);
  });

  it('refuses a key it never issued, a malformed one, and an expired one', () => {
    const licences = store();
    const { record } = issueLicence(licences, { plan: 'pro', sessionId: 'cs_3', now: 0 });

    assert.equal(verifyLicence(licences, 'CA-ZZZZ-ZZZZ-ZZZZ-ZZZZ').reason, 'UNKNOWN_KEY');
    assert.equal(verifyLicence(licences, 'nonsense').reason, 'MALFORMED_KEY');
    assert.equal(
      verifyLicence(licences, record.key, { now: record.expiresAt + 1 }).reason,
      'EXPIRED',
    );
  });

  it('refuses one that was cancelled or refunded', () => {
    const licences = store();
    const { record } = issueLicence(licences, { plan: 'pro', sessionId: 'cs_4' });
    revokeLicence(licences, record, { reason: 'refunded' });

    const answer = verifyLicence(licences, record.key);
    assert.equal(answer.valid, false);
    assert.equal(answer.reason, 'REFUNDED');
  });
});

describe('what a Stripe event means', () => {
  it('issues on a paid checkout, and not on an unpaid one', () => {
    const paid = decideFromEvent(JSON.parse(completedSession()));
    assert.equal(paid.action, 'issue');
    assert.equal(paid.plan, 'pro');
    assert.equal(paid.email, 'dpo@example.fr');
    assert.equal(paid.subscriptionId, 'sub_test_1');

    const unpaid = decideFromEvent(JSON.parse(completedSession({ payment_status: 'unpaid' })));
    assert.equal(unpaid.action, 'ignore');
  });

  it('revokes on a cancelled subscription and on a refund', () => {
    assert.equal(
      decideFromEvent({ type: 'customer.subscription.deleted', data: { object: { id: 'sub_1' } } }).action,
      'revoke',
    );
    assert.equal(
      decideFromEvent({ type: 'charge.refunded', data: { object: { customer: 'cus_1' } } }).action,
      'revoke',
    );
  });

  it('ignores what it does not handle rather than failing on it', () => {
    /* Stripe retries an endpoint that errors and eventually disables it, which
       would take the events that matter with it. */
    const decision = decideFromEvent({ type: 'invoice.upcoming', data: { object: {} } });
    assert.equal(decision.action, 'ignore');
    assert.match(decision.reason, /invoice.upcoming/);
  });
});

describe('POST /stripe/webhook', () => {
  it('issues a licence on a signed, paid checkout', async () => {
    const server = await start();
    try {
      const body = completedSession();
      const response = await post(server.origin, '/stripe/webhook', body, {
        'stripe-signature': sign(body),
      });
      const payload = await response.json();

      assert.equal(response.status, 200);
      assert.equal(payload.data.action, 'issue');
      assert.equal(payload.data.plan, 'pro');

      const issued = server.licences.all();
      assert.equal(issued.length, 1);
      assert.equal(issued[0].email, 'dpo@example.fr');
      assert.equal(issued[0].status, 'active');
    } finally {
      await server.close();
    }
  });

  it('refuses an unsigned body, a wrongly signed one, and a replayed one', async () => {
    const server = await start();
    try {
      const body = completedSession();

      const unsigned = await post(server.origin, '/stripe/webhook', body);
      assert.equal(unsigned.status, 400);

      const wrong = await post(server.origin, '/stripe/webhook', body, {
        'stripe-signature': sign('{"tampered":true}'),
      });
      assert.equal(wrong.status, 400);

      /* Stripe's tolerance is five minutes; an hour-old signature is a replay. */
      const old = await post(server.origin, '/stripe/webhook', body, {
        'stripe-signature': sign(body, Math.floor(Date.now() / 1000) - 3600),
      });
      assert.equal(old.status, 400);

      assert.equal(server.licences.all().length, 0, 'a licence was issued without a valid signature');
    } finally {
      await server.close();
    }
  });

  it('issues once for a webhook delivered twice', async () => {
    const server = await start();
    try {
      const body = completedSession();
      const first = await (await post(server.origin, '/stripe/webhook', body, { 'stripe-signature': sign(body) })).json();
      const second = await (await post(server.origin, '/stripe/webhook', body, { 'stripe-signature': sign(body) })).json();

      assert.equal(first.data.reissued, false);
      assert.equal(second.data.reissued, true);
      assert.equal(server.licences.all().length, 1);
    } finally {
      await server.close();
    }
  });

  it('revokes the licence when the subscription ends', async () => {
    const server = await start();
    try {
      const created = completedSession();
      await post(server.origin, '/stripe/webhook', created, { 'stripe-signature': sign(created) });

      const cancelled = JSON.stringify({
        id: 'evt_test_2',
        type: 'customer.subscription.deleted',
        data: { object: { id: 'sub_test_1' } },
      });
      const response = await post(server.origin, '/stripe/webhook', cancelled, {
        'stripe-signature': sign(cancelled),
      });

      assert.equal((await response.json()).data.found, true);
      assert.equal(server.licences.all()[0].status, 'cancelled');
    } finally {
      await server.close();
    }
  });

  it('answers 200 to an event it does not handle', async () => {
    const server = await start();
    try {
      const body = JSON.stringify({ id: 'evt_3', type: 'invoice.paid', data: { object: {} } });
      const response = await post(server.origin, '/stripe/webhook', body, {
        'stripe-signature': sign(body),
      });
      assert.equal(response.status, 200);
    } finally {
      await server.close();
    }
  });
});

describe('POST /licence/verify', () => {
  it('answers 200 with valid:false for a bad key, not an error', async () => {
    /* A client that cannot tell "your key is wrong" from "the service is down"
       will do the wrong thing about it — the first is final, the second is
       what the grace period exists for. */
    const server = await start();
    try {
      const response = await post(server.origin, '/licence/verify', { key: 'CA-ZZZZ-ZZZZ-ZZZZ-ZZZZ' });
      const payload = await response.json();

      assert.equal(response.status, 200);
      assert.equal(payload.ok, true);
      assert.equal(payload.data.valid, false);
      assert.equal(payload.data.reason, 'UNKNOWN_KEY');
    } finally {
      await server.close();
    }
  });

  it('answers a real key with the plan and the dates', async () => {
    const server = await start();
    try {
      const body = completedSession();
      await post(server.origin, '/stripe/webhook', body, { 'stripe-signature': sign(body) });
      const key = server.licences.all()[0].key;

      const payload = await (await post(server.origin, '/licence/verify', { key })).json();
      assert.equal(payload.data.valid, true);
      assert.equal(payload.data.plan, 'pro');
      assert.ok(payload.data.recheckAfter > Date.now());
      assert.equal(payload.data.plans.free.auditsPerMonth, 5);
    } finally {
      await server.close();
    }
  });
});

describe('the analysis endpoint, once licences are sold', () => {
  const POLICY = `Fixture SAS, 12 rue de la Paix, Paris, is the controller for the data processed through this website, and can be reached at contact@fixture.example for any question about it.

We process browsing data, your IP address and the identifiers stored on your device in order to measure our audience and to deliver advertising, and we keep all of it for thirteen months from collection.

You may withdraw your consent at any time through the link in the footer of every page, and you may lodge a complaint with the CNIL.`;

  it('refuses without a licence, and says which plan is needed', async () => {
    const server = await start();
    try {
      const refused = await post(server.origin, '/analyze-policy', { text: POLICY });
      assert.equal(refused.status, 402);
      assert.equal((await refused.json()).error.code, 'LICENCE_MALFORMED_KEY');
    } finally {
      await server.close();
    }
  });

  it('accepts with one', async () => {
    const server = await start();
    try {
      const body = completedSession();
      await post(server.origin, '/stripe/webhook', body, { 'stripe-signature': sign(body) });
      const key = server.licences.all()[0].key;

      const response = await post(server.origin, '/analyze-policy', { text: POLICY, licenceKey: key });
      assert.equal(response.status, 200);
      assert.equal((await response.json()).ok, true);
    } finally {
      await server.close();
    }
  });

  it('still serves a deployment that sells nothing', async () => {
    /* Self-hosting is a real case: no licences, no Stripe, the operator's own
       key and their own bearer token. */
    const server = await start({ licences: null, billing: null });
    try {
      const response = await post(server.origin, '/analyze-policy', { text: POLICY });
      assert.equal(response.status, 200);

      const checkout = await post(server.origin, '/checkout', { plan: 'pro' });
      assert.equal(checkout.status, 503);
    } finally {
      await server.close();
    }
  });
});

describe('POST /checkout', () => {
  it('returns the URL the extension opens', async () => {
    const server = await start();
    try {
      const payload = await (await post(server.origin, '/checkout', { plan: 'pro' })).json();
      assert.equal(payload.ok, true);
      assert.match(payload.data.url, /^https:\/\/checkout\.stripe\.test\//);
    } finally {
      await server.close();
    }
  });

  it('reports a plan it has no price for as the caller’s mistake', async () => {
    const server = await start({
      billing: billingDouble({
        createCheckout: async () => {
          const error = new Error('No price configured for plan "gold"');
          error.code = 'UNKNOWN_PLAN';
          error.name = 'BillingError';
          throw error;
        },
      }),
    });
    try {
      const response = await post(server.origin, '/checkout', { plan: 'gold' });
      assert.equal(response.status, 502);
    } finally {
      await server.close();
    }
  });
});
